apiVersion: v2
name: jupyterhub-custom
description: Wrapper around jupyterhub/jupyterhub chart
version: 0.1.0

dependencies:
  - name: jupyterhub
    version: "3.2.1"
    repository: "https://jupyterhub.github.io/helm-chart"


# helm dependency update /Users/joshuaagar/PyKubeGrader/src/jupyterhub/chart.yml
