JHUB:
  subdomain-name: "testing-agar-jhub"
  domain-name: nrp-nautilius.io
  admin_users:
    - jca92
  oauth_callback_url: https://your_name.nrp-nautilus.io/hub/oauth_callback
  globus:
    client_id: "3d282aef-5ee7-40c9-88f0-c89cb5582e41"
    client_secret: "3d282aef-5ee7-40c9-88f0-c89cb5582e41@clients.auth.globus.org"
  image_spec: quay.io/jupyter/scipy-notebook:2024-04-22