apiVersion: v1
hub:
  config:
    JupyterHub:
      authenticator_class: "oauthenticator.globus.GlobusOAuthenticator"
    Authenticator:
      allow_all: true
      admin_users: ["jca92"]
    GlobusOAuthenticator:
      oauth_callback_url: "https://{{.Values.JHUB.subdomain_name}}.{{.Values.JHUB.domain_name}}/hub/oauth_callback"
      client_id: {{.Values.JHUB.globus.client_id}}
      client_secret: {{ .Values.JHUB.globus.client_secret}}
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  deploymentStrategy:
    type: Recreate
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: rook-ceph-block
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  networkPolicy:
    enabled: false
proxy:
  secretToken: "secret_token"
  service:
    type: ClusterIP
  chp:
    resources:
      limits:
        cpu: "6"
        memory: 10Gi
      requests:
        cpu: "1"
        memory: 512Mi
singleuser:
  uid: 0
  fsGid: 100
  extraEnv:
    GRANT_SUDO: "yes"
  extraPodConfig:
    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"
      fsGroup: 100
  extraNodeAffinity:
    required:
      - matchExpressions:
          - "key": "topology.kubernetes.io/region"
            "operator": "In"
            "values": ["us-west"]
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    capacity: 5Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: rook-ceph-block
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: quay.io/jupyter/scipy-notebook
    tag: 2024-04-22
  startTimeout: 600
  cpu:
    limit: 3
    guarantee: 3
  memory:
    limit: 10G
    guarantee: 10G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: null
  defaultUrl: "/lab"
  profileList:
    - display_name: Course
      kubespawner_override:
        image_spec: {{ .Values.image_spec }}
      default: True

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

# prePuller relates to the hook|continuous-image-puller DaemonsSets
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
  hosts: ["{{.Values.JHUB.subdomain_name}}.{{.Values.JHUB.domain_name}}"]
  pathSuffix: ""
  tls:
    - hosts:
        - "{{.Values.JHUB.subdomain_name}}.{{.Values.JHUB.domain_name}}"

cull:
  enabled: true
  users: false
  removeNamedServers: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
