apiVersion: v2
kind: Service
hub:
  config:
    CILogonOAuthenticator:
      client_id: {{ .Values.JHUB.cilogon.client_id | quote }}
      client_secret: {{ .Values.JHUB.cilogon.client_secret | quote }}
      oauth_callback_url: "https://{{ .Values.JHUB.cilogon.subdomain_name }}.{{ .Values.JHUB.cilogon.domain_name }}/hub/oauth_callback"
      admin_users:
        - {{ index .Values.JHUB.jupyterhub.admin_users 0 | quote }}
      allowed_idps:
        https://shib.unl.edu/idp/shibboleth:
          allowed_domains:
            - drexel.edu
          username_derivation:
            username_claim: email
    JupyterHub:
      admin_access: true
      admin_users: {{ toJson .Values.JHUB.jupyterhub.admin_users }}
      authenticator_class: cilogon
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  deploymentStrategy:
    type: Recreate
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: rook-ceph-block
  resources:
    limits:
      cpu: "2"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  networkPolicy:
    enabled: false
proxy:
  secretToken: "secret_token"
  service:
    type: ClusterIP
  chp:
    resources:
      limits:
        cpu: "6"
        memory: 10Gi
      requests:
        cpu: "1"
        memory: 512Mi
singleuser:
  uid: 0
  fsGid: 100
  extraEnv:
    GRANT_SUDO: "yes"
  extraPodConfig:
    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"
      fsGroup: 100
  extraNodeAffinity:
    required:
      - matchExpressions:
          - "key": "topology.kubernetes.io/region"
            "operator": "In"
            "values": ["us-west"]
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    capacity: 5Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: rook-ceph-block
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: quay.io/jupyter/scipy-notebook
    tag: 2024-04-22
  startTimeout: 600
  cpu:
    limit: 3
    guarantee: 3
  memory:
    limit: 10G
    guarantee: 10G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: null
  defaultUrl: "/lab"
  profileList:
    - display_name: Scipy
      kubespawner_override:
        image_spec: quay.io/jupyter/scipy-notebook:2024-04-22
      default: True
    - display_name: R
      kubespawner_override:
        image_spec: quay.io/jupyter/r-notebook:2024-04-22
    - display_name: Julia
      kubespawner_override:
        image_spec: quay.io/jupyter/julia-notebook:2024-04-22
    - display_name: Tensorflow
      kubespawner_override:
        image_spec: quay.io/jupyter/tensorflow-notebook:cuda-2024-04-22
    - display_name: Pytorch
      kubespawner_override:
        image_spec: quay.io/jupyter/pytorch-notebook:cuda12-2024-04-22
    - display_name: Datascience (scipy, Julia, R)
      kubespawner_override:
        image_spec: quay.io/jupyter/datascience-notebook:2024-04-22
    - display_name: Pyspark
      kubespawner_override:
        image_spec: quay.io/jupyter/pyspark-notebook:2024-04-22
    - display_name: All Spark
      kubespawner_override:
        image_spec: quay.io/jupyter/all-spark-notebook:2024-04-22
    - display_name: B-Data python scipy
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/python/scipy:3
    - display_name: B-Data Julia
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/julia/base:1
    - display_name: B-Data R
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/r/base:4
    - display_name: B-Data R tidyverse
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/r/tidyverse:4
    - display_name: B-Data R verse
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/r/verse:4
    - display_name: B-Data R geospatial
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/r/geospatial:4
    - display_name: B-Data R qgisprocess
      kubespawner_override:
        image_spec: glcr.b-data.ch/jupyterlab/cuda/r/qgisprocess:4

scheduling:
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: false

# prePuller relates to the hook|continuous-image-puller DaemonsSets
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
  hosts:
    - "{{ .Values.JHUB.cilogon.subdomain_name }}.{{ .Values.JHUB.cilogon.domain_name }}"
  pathSuffix: ""
  tls:
    - hosts:
        - "{{ .Values.JHUB.cilogon.subdomain_name }}.{{ .Values.JHUB.cilogon.domain_name }}"

cull:
  enabled: true
  users: false
  removeNamedServers: false
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 0
